import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import dynamic from "next/dynamic";

const MapApp = dynamic(
  () => import("@/components/MapApp").then((mod) => mod.MapApp),
  {
    loading: () => <div>Loading map...</div>,
    ssr: false,
  }
);

const inter = Inter({ subsets: ["latin"], weight: "300" });

export default function Home() {
  return (
    <>
      <Head>
        <title>dem-liner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className} ${styles.main}`}>
        <MapApp />
      </main>
    </>
  );
}
